/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.distributeur.Vue.VirementBancaire;

import client.distributeur.Payement;
import client.distributeur.Vue.Menu.MenuDistributeur;
import java.text.DateFormat;

/**
 *
 * @author Aurore
 */
public class PaiementValide extends javax.swing.JFrame {

    static private Payement payement;
    
    /**
     * Creates new form PaiementValide
     */
    public PaiementValide(Payement payement) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.payement = payement;
        
        DateFormat shortDateFormat = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT);
        
        String recepisse = "Numéro du virement : " + payement.getNumPayement() + "\n" +
                            "Numéro du compte débité : " + payement.getNumComptePayeur() + "\n" +
                            "Numéro du compte crédité : " + payement.getNumCompteReception() + "\n" +
                            "Montant du virement : " + payement.getMontant() + " €\n" +
                            "Date du virement : " + shortDateFormat.format(payement.getDate());
        jTextAreaRecepisse.setText(recepisse);
        jTextAreaRecepisse.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRecepisse = new javax.swing.JLabel();
        jLabelPaiementValide = new javax.swing.JLabel();
        jLabelPensezCopier = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jScrollPaneRecepisse = new javax.swing.JScrollPane();
        jTextAreaRecepisse = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paiement validé");

        jLabelRecepisse.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelRecepisse.setText("Récépissé");

        jLabelPaiementValide.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelPaiementValide.setText("Votre paiement est validé !");

        jLabelPensezCopier.setText("Pensez à copier le récépissé comme preuve d'achat.");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jTextAreaRecepisse.setColumns(20);
        jTextAreaRecepisse.setRows(5);
        jScrollPaneRecepisse.setViewportView(jTextAreaRecepisse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jButtonOK))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPaiementValide)
                                    .addComponent(jLabelRecepisse)
                                    .addComponent(jLabelPensezCopier))))
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPaneRecepisse)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaiementValide)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecepisse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneRecepisse, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPensezCopier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        MenuDistributeur menuDistributeur = new MenuDistributeur();
        menuDistributeur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaiementValide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaiementValide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaiementValide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaiementValide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaiementValide(payement).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelPaiementValide;
    private javax.swing.JLabel jLabelPensezCopier;
    private javax.swing.JLabel jLabelRecepisse;
    private javax.swing.JScrollPane jScrollPaneRecepisse;
    private javax.swing.JTextArea jTextAreaRecepisse;
    // End of variables declaration//GEN-END:variables
}
