/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import javax.swing.DefaultListModel;
import presse.motsCles;

/**
 *
 * @author Manon
 */
public class Detail extends javax.swing.JFrame {

    /**
     * Creates new form Detail
     */
    public Detail() {
        initComponents();
        
        //Dimensionnement Fenetre
        setLocationRelativeTo(null);
        
    }
    
    //Permet d'alimenter les champs à partir des informations reçues du serveur
    public void setChamp(String nomArt, String contenu, String nomAut, HashMap<Integer,motsCles> listeMC){
        //Alimentation des champs Nom de l'article et Nom de l'auteur
        jTextField_NomDetailArticle.setText(nomArt);
        jTextField_AuteurDetailArticle.setText(nomAut);
        
        //Alimentation de la liste des mots-clés
        DefaultListModel modele = (DefaultListModel) jList_MotsClesDetailArticle.getModel();
        Set clesMC = listeMC.keySet();
            Iterator itMC = clesMC.iterator();
            while (itMC.hasNext()){
                Object cle = itMC.next();
                String motscles = listeMC.get(cle).getMotCle();
                String strMC = motscles.replaceAll("\\[", "").replaceAll("\\]","");
                modele.addElement(strMC);
            }
        
        //Alimentation du champ Contenu
        jTextArea_ContenuDetailArticle.setText(contenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_DetailArticle = new javax.swing.JPanel();
        jLabel_NomDetailArticle = new javax.swing.JLabel();
        jTextField_NomDetailArticle = new javax.swing.JTextField();
        jTextField_AuteurDetailArticle = new javax.swing.JTextField();
        jLabel_AuteurDetailArticle = new javax.swing.JLabel();
        jLabel_ContenuDetailArticle = new javax.swing.JLabel();
        jScrollPane_ContenuDetailArticle = new javax.swing.JScrollPane();
        jTextArea_ContenuDetailArticle = new javax.swing.JTextArea();
        jScrollPane_MotsClesDetailArticle = new javax.swing.JScrollPane();
        jList_MotsClesDetailArticle = new javax.swing.JList<>();
        jLabel_MotsClesDetailArticle = new javax.swing.JLabel();
        jButton_FermerDetailArticle = new javax.swing.JButton();

        jLabel_NomDetailArticle.setText("Nom : ");

        jTextField_NomDetailArticle.setEditable(false);

        jTextField_AuteurDetailArticle.setEditable(false);

        jLabel_AuteurDetailArticle.setText("Auteur :");

        jLabel_ContenuDetailArticle.setText("Contenu :");

        jTextArea_ContenuDetailArticle.setEditable(false);
        jTextArea_ContenuDetailArticle.setColumns(20);
        jTextArea_ContenuDetailArticle.setLineWrap(true);
        jTextArea_ContenuDetailArticle.setRows(5);
        jScrollPane_ContenuDetailArticle.setViewportView(jTextArea_ContenuDetailArticle);

        jList_MotsClesDetailArticle.setModel(new DefaultListModel());
        jList_MotsClesDetailArticle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane_MotsClesDetailArticle.setViewportView(jList_MotsClesDetailArticle);

        jLabel_MotsClesDetailArticle.setText("Mots-clés :");

        jButton_FermerDetailArticle.setText("Fermer");
        jButton_FermerDetailArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FermerDetailArticleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_DetailArticleLayout = new javax.swing.GroupLayout(jPanel_DetailArticle);
        jPanel_DetailArticle.setLayout(jPanel_DetailArticleLayout);
        jPanel_DetailArticleLayout.setHorizontalGroup(
            jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DetailArticleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DetailArticleLayout.createSequentialGroup()
                        .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NomDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_AuteurDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(347, 347, 347))
                    .addGroup(jPanel_DetailArticleLayout.createSequentialGroup()
                        .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ContenuDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_MotsClesDetailArticle))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_ContenuDetailArticle)
                            .addGroup(jPanel_DetailArticleLayout.createSequentialGroup()
                                .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane_MotsClesDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_NomDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_AuteurDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel_DetailArticleLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton_FermerDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_DetailArticleLayout.setVerticalGroup(
            jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DetailArticleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NomDetailArticle)
                    .addComponent(jTextField_NomDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AuteurDetailArticle)
                    .addComponent(jTextField_AuteurDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ContenuDetailArticle)
                    .addComponent(jScrollPane_ContenuDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DetailArticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_MotsClesDetailArticle)
                    .addComponent(jScrollPane_MotsClesDetailArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_FermerDetailArticle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_DetailArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_DetailArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FermerDetailArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FermerDetailArticleActionPerformed
        // TODO add your handling code here:
        //Fermeture de la fenêtre
        this.setVisible(false);
    }//GEN-LAST:event_jButton_FermerDetailArticleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_FermerDetailArticle;
    private javax.swing.JLabel jLabel_AuteurDetailArticle;
    private javax.swing.JLabel jLabel_ContenuDetailArticle;
    private javax.swing.JLabel jLabel_MotsClesDetailArticle;
    private javax.swing.JLabel jLabel_NomDetailArticle;
    private javax.swing.JList<String> jList_MotsClesDetailArticle;
    private javax.swing.JPanel jPanel_DetailArticle;
    private javax.swing.JScrollPane jScrollPane_ContenuDetailArticle;
    private javax.swing.JScrollPane jScrollPane_MotsClesDetailArticle;
    private javax.swing.JTextArea jTextArea_ContenuDetailArticle;
    private javax.swing.JTextField jTextField_AuteurDetailArticle;
    private javax.swing.JTextField jTextField_NomDetailArticle;
    // End of variables declaration//GEN-END:variables
}
